### ISSUE TITLE
Error running =install_dependencies.py

### ISSUE THREAD

**Issue by sashalazetic** [lauringlab/CodonShuffle#6]
Hi, I am trying to run install_dependencies.py and get the following error message. If anyone can provide suggestions I'd be eternally grateful. Ty.

I did have Python2.7.9 installed for Pymol, uninstalled 2.7.9 and installed 2.7.10.
I am on Windows 10 Pro and Python 2.7.10 is running my install of Pymol without issue.
My sytem environmental variable path has been set to C:\Python27
I've tried running install_dependencies.py from either my c:/Python27 forlder or the CodonShuffle folder with the same error

Error message when running install_dependencies.py from the command line:
C:\Users\SashaLazetic\Desktop\CodonShuffle-master>install_dependencies.py
Traceback (most recent call last):
  File "C:\Users\SashaLazetic\Desktop\CodonShuffle-master\install_dependencies.py", line 3, in <module>
    subprocess.call(['pip', 'install', 'numpy']) # Install Numpy
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by sashalazetic** [comment]
I've figured out some of my issues with the install file, but am still running into errors installing Statsmodels:

C:\Python27\Scripts>pip install statsmodels
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting statsmodels
  Using cached statsmodels-0.11.0.tar.gz (15.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pandas>=0.21 in c:\python27\lib\site-packages (from statsmodels) (0.24.2)
Requirement already satisfied: scipy>=1.0 in c:\python27\lib\site-packages (from statsmodels) (1.2.3)
Requirement already satisfied: numpy>=1.14 in c:\python27\lib\site-packages (from statsmodels) (1.16.6)
Requirement already satisfied: patsy>=0.5 in c:\python27\lib\site-packages (from statsmodels) (0.5.1)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\python27\lib\site-packages (from pandas>=0.21->statsmodels) (2.8.1)
Requirement already satisfied: pytz>=2011k in c:\python27\lib\site-packages (from pandas>=0.21->statsmodels) (2020.1)
Requirement already satisfied: six in c:\python27\lib\site-packages (from patsy>=0.5->statsmodels) (1.14.0)
Building wheels for collected packages: statsmodels
  Building wheel for statsmodels (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Python27\python.exe' 'C:\Python27\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'c:\users\sashal~1\appdata\local\temp\tmp12gg9k'
       cwd: c:\users\sashal~1\appdata\local\temp\pip-install-cnjso0\statsmodels
  Complete output (1367 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
